# Generated by Django 3.0.1 on 2020-02-09 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200125_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='instanct_book',
            new_name='instant_book',
        ),
    ]
